name: Deploy Autodesk Viewer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace token and URN in app.js
        run: |
          sed -i 's/YOUR_ACCESS_TOKEN/${{ secrets.FORGE_ACCESS_TOKEN }}/' app.js
          sed -i 's/YOUR_URN_ID/dXJuOmFkc2sud2lwLmZvcmdlLmFwaS5jb20vc2FtcGxlLnJ2dA/' app.js  # Replace with your actual URN if known, or keep this sample

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust if necessary
