name: Deploy Autodesk Viewer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Reset git state
        run: |
          git reset --hard
          git clean -fdx

      - name: Replace token in app.js
        run: |
          sed -i 's/YOUR_ACCESS_TOKEN/${{ secrets.FORGE_ACCESS_TOKEN }}/' app.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Ensure this directory is correct
